Adding weekly tpr and vaccination coverage to final data
whocov/trend_analysis_public pull request #30
Opened 2021-07-02 14:53 UTC by henryls1

Created a pull request to add TPR and Vaccination coverage data to the ELR spreadsheet. 

Process is as follows:

1. Data to be appended are saved in separate .rds to `final_data.rds` in `assemble_data.Rmd`
2. Data are loaded in `elr_review.Rmd`, and merged with final data, before saving in the final spreadsheet

2021-07-03 10:54 UTC, thibautjombart requested changes
Thanks a lot for this! Looks like one object is missing or might have been renamed, hopefully a small fix?

2021-07-03 10:54 UTC, thibautjombart commented on report_sources/elr_review.Rmd
> +     left_join(elr_extras_final, by = "iso3")
It looks like this is the first time 'elr_extras_final' is defined, which causes the following error on my end when compiling the Rmd:
```
label: unnamed-chunk-18
Quitting from lines 572-612 (elr_review.Rmd) 
Error in is.data.frame(y) : object 'elr_extras_final' not found
```

2021-07-05 08:17 UTC, henryls1 commented
My bad on that erorr - all fixed now @thibautjombart

2021-07-05 08:40 UTC, thibautjombart approved these changes
Works for me. Document compiles fine and the outputs make sense, though I think the tpr reported in the leaderboard of the report may still be the 'old' one. @nsbatra there are now quite a few new columns in the exported xlsx, can you check if you want to keep all of them or just a subset?

2021-07-05 08:44 UTC, merged